"""Agrego columnas nuevas a la tabla de modelos

Revision ID: 1751fa0b8066
Revises: ed8d2bb160e6
Create Date: 2024-05-11 04:28:11.240219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1751fa0b8066'
down_revision: Union[str, None] = 'ed8d2bb160e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('type_accuount', sa.String(), nullable=False))
    op.add_column('models', sa.Column('number_account', sa.String(length=12), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'number_account')
    op.drop_column('models', 'type_accuount')
    # ### end Alembic commands ###
