"""Agrego una nueva columna a accounts

Revision ID: 4a50dd5c6afd
Revises: 6590c30ef2e7
Create Date: 2024-05-19 21:46:33.284952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a50dd5c6afd'
down_revision: Union[str, None] = '6590c30ef2e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('api_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'api_token')
    # ### end Alembic commands ###
