"""agrego una tabla tokens2

Revision ID: 96b86a4f7ef5
Revises: 51bee0f7c457
Create Date: 2024-05-12 10:20:57.717583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b86a4f7ef5'
down_revision: Union[str, None] = '51bee0f7c457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
