"""Corrijo error de nombre en la tabla modelos

Revision ID: b9e7962837d6
Revises: 1751fa0b8066
Create Date: 2024-05-11 04:35:12.721367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9e7962837d6'
down_revision: Union[str, None] = '1751fa0b8066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('type_account', sa.String(), nullable=False))
    op.drop_column('models', 'type_accuount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('type_accuount', sa.VARCHAR(), nullable=False))
    op.drop_column('models', 'type_account')
    # ### end Alembic commands ###
