"""agrego una tabla tokens4

Revision ID: c754eaf0055f
Revises: e21ae5485e21
Create Date: 2024-05-12 10:28:30.854056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c754eaf0055f'
down_revision: Union[str, None] = 'e21ae5485e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
