"""agrego una tabla tokens3

Revision ID: e21ae5485e21
Revises: 96b86a4f7ef5
Create Date: 2024-05-12 10:22:14.557449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e21ae5485e21'
down_revision: Union[str, None] = '96b86a4f7ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
